---
apiVersion: v1
kind: Namespace
metadata:
  name: argo-rollouts
  labels:
    name: argo-rollouts

---
apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: HelmRepository
metadata:
  name: argo
  namespace: flux-system
spec:
  interval: 1h0m0s
  url: https://argoproj.github.io/argo-helm

---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: argo-rollouts
  namespace: flux-system
spec:
  chart:
    spec:
      chart: argo-rollouts
      sourceRef:
        kind: HelmRepository
        name: argo
  install:
    crds: Create
  interval: 1h0m0s
  releaseName: argo-rollouts
  targetNamespace: argo-rollouts
  upgrade:
    crds: CreateReplace

