---
apiVersion: v1
kind: Namespace
metadata:
  name: project
  labels:
    name: project

---
apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: GitRepository
metadata:
  name: uh-devops-with-kubernetes
  namespace: flux-system
spec:
  interval: 5m
  ref:
    branch: release
  url: https://github.com/kekalainen/uh-devops-with-kubernetes

---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta1
kind: Kustomization
metadata:
  name: project-app
  namespace: flux-system
spec:
  sourceRef:
    kind: GitRepository
    name: uh-devops-with-kubernetes
  interval: 5m
  path: ./project-app
  prune: true
  validation: client

